// ============================================================
//  CareQueue — lang.dart
//  Language Service: English | Tamil | Sinhala
//  Usage: Lang.t('key')  →  returns translated string
// ============================================================

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ── Language codes ───────────────────────────────────────────
enum AppLang { en, ta, si }

// ── Global notifier (whole app rebuilds when lang changes) ───
final langNotifier = ValueNotifier<AppLang>(AppLang.en);

class Lang {
  static AppLang get current => langNotifier.value;

  // ── Load saved language from device ──────────────────────
  static Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final code  = prefs.getString('app_lang') ?? 'en';
    langNotifier.value = code == 'ta' ? AppLang.ta
                       : code == 'si' ? AppLang.si
                       : AppLang.en;
  }

  // ── Save + switch language ────────────────────────────────
  static Future<void> set(AppLang lang) async {
    langNotifier.value = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_lang', lang.name);
  }

  // ── Translate ─────────────────────────────────────────────
  static String t(String key) {
    final map = _strings[current];
    return map?[key] ?? _strings[AppLang.en]?[key] ?? key;
  }

  // ══════════════════════════════════════════════════════════
  //  ALL TRANSLATIONS
  // ══════════════════════════════════════════════════════════
  static const Map<AppLang, Map<String, String>> _strings = {

    // ─────────────────────────────────────────────────────────
    //  ENGLISH
    // ─────────────────────────────────────────────────────────
    AppLang.en: {

      // App
      'app_name':             'CareQueue',
      'app_tagline':          'Sri Murugan Clinic',

      // Language names (shown in switcher)
      'lang_en':              'EN',
      'lang_ta':              'தமிழ்',
      'lang_si':              'සිංහල',

      // Common
      'loading':              'Loading...',
      'success':              'Success',
      'error':                'Error',
      'cancel':               'Cancel',
      'save':                 'Save',
      'delete':               'Delete',
      'confirm':              'Confirm',
      'yes':                  'Yes',
      'no':                   'No',
      'back':                 'Back',
      'ok':                   'OK',
      'close':                'Close',
      'logout':               'Logout',
      'or':                   'or',

      // Nav tabs
      'tab_book':             'Book',
      'tab_queue':            'Live Queue',
      'tab_profile':          'Profile',
      'nav_book':             'Book',
      'nav_live':             'Live Queue',
      'nav_profile':          'Profile',

      // ── Patient Auth ──────────────────────────────────────
      'login':                'Login',
      'register':             'Register',
      'create_account':       '+ Create Account',
      'already_account':      'Already have an account?',
      'welcome_back':         'Welcome Back',

      // Login
      'login_title':          '🔐 Login',
      'gmail_label':          'Gmail',
      'gmail_hint':           'yourgmail',
      'gmail_suffix':         '@gmail.com',
      'password_label':       'Password',
      'password_hint':        '••••••••',
      'login_btn':            '🚀 Login',

      // Register
      'reg_title':            'Register',
      'personal_details':     '📋 Personal Details',
      'fullname_label':       'Full Name *',
      'fullname_hint':        'Your full name (English only)',
      'nic_label':            'NIC *',
      'nic_hint':             '901234567V or 200012345678',
      'phone_label':          'Phone *',
      'phone_hint':           '0756160070',
      'clinic_details':       '🏥 Clinic Details',
      'patient_id_label':     'Patient Card ID *',
      'patient_id_hint':      'P-0001',
      'password_section':     '🔐 Password',
      'confirm_pass_label':   'Confirm Password *',
      'confirm_pass_hint':    'Re-enter password',
      'min_pass_hint':        'Min 6 characters',
      'register_btn':         '✅ Register',
      'registered_clinic':    'Registered Clinic',
      'patient_id_hint_info': '💡 Your Patient Card ID given by clinic staff (e.g. P-0001)',
      'err_login_both':       'Please enter Gmail and Password',

      // Validation errors
      'err_name_empty':       '❌ Please enter your name',
      'err_name_english':     '❌ English letters only (a-z, A-Z)',
      'err_nic_empty':        '❌ Please enter NIC',
      'err_nic_format':       '❌ 12 digits (new) or 9 digits + V (e.g. 901234567V)',
      'err_phone_empty':      '❌ Please enter phone number',
      'err_phone_format':     '❌ Must start with 07, 10 digits (e.g. 0756160070)',
      'err_gmail_empty':      '❌ Please enter Gmail',
      'err_gmail_format':     '❌ Enter valid Gmail username',
      'err_patid_empty':      '❌ Please enter Patient ID (e.g. P-0001)',
      'err_patid_format':     '❌ Format: P-0001 (P capital, 4 digits)',
      'err_pass_empty':       '❌ Minimum 6 characters required',
      'err_pass_match':       '❌ Passwords do not match',
      'err_login_gmail':      '❌ Please enter Gmail',
      'err_login_pass':       '❌ Please enter Password',

      // ── Patient Home ──────────────────────────────────────
      'available_dates':      'Available Clinic Dates',
      'dates_subtitle':       'Only doctor-set dates are shown',
      'book_btn':             '🎫 Book Token',
      'selected':             'Selected ✅',
      'max_label':            'Max',
      'booked_label':         'booked',
      'no_dates':             'No clinic dates available yet.\nDoctor will set dates soon.',
      'booking_open':         'Book Now ✅',
      'booking_closed':       'Booking not open yet',
      'already_booked':       'Already Booked ✅',
      'book_success':         '🎉 Token booked! Your token:',
      'book_error':           '❌ Booking failed. Try again.',
      'date_not_found':       '❌ Date not found!',

      // ── Live Queue ────────────────────────────────────────
      'live_queue_title':     'Live Queue',
      'my_bookings':          'My Bookings',
      'current_token':        'Current Token',
      'your_token':           'Your Token',
      'patients_ahead':       'patients ahead',
      'your_turn':            '🎉 It\'s Your Turn!',
      'status_waiting':       'Waiting',
      'status_done':          'Done',
      'status_skipped':       'Skipped',
      'no_bookings':          'No bookings yet.\nBook a token from the Book tab.',
      'clinic_name':          'Clinic',
      'booking_date':         'Date',
      'token_no':             'Token',
      'status_label':         'Status',

      // ── Profile ───────────────────────────────────────────
      'profile_title':        'My Profile',
      'edit_profile':         'Edit Profile',
      'name_label':           'Full Name',
      'nic_info':             'NIC',
      'phone_info':           'Phone',
      'patient_id':           'Patient ID',
      'change_password':      'Change Password',
      'old_pass_label':       'Current Password',
      'new_pass_label':       'New Password',
      'update_btn':           'Update Profile',
      'delete_account':       '🗑️ Delete Account',
      'delete_confirm':       'Are you sure you want to delete your account? This cannot be undone.',
      'delete_pass_hint':     'Enter password to confirm',
      'update_success':       '✅ Profile updated!',
      'delete_success':       '✅ Account deleted.',

      // ── Doctor Auth ───────────────────────────────────────
      'doc_login_title':      'Doctor Login',
      'clinic_id_label':      'Clinic ID',
      'clinic_id_hint':       'CLN-XXXX-XXX',
      'doc_name_label':       'Doctor Name',
      'doc_name_hint':        'Dr. Your Name (English only)',
      'doc_login_btn':        '🏥 Doctor Login',
      'tap_to_fill':          'Tap to fill demo credentials',
            'demo_clinic_id':       'Demo Clinic ID',
      'doc_login_sub':        'Use clinic-assigned credentials only',
      'demo_password_label':  'Password: doctor123',
      'doc_login_card':       '🔐 DOCTOR LOGIN',
      'doc_login_note':       'Only clinic staff can log in. Contact your clinic admin if you do not have your credentials.',
      'err_cid_empty':        '❌ Please enter your Clinic ID',
      'err_dpass_empty':      '❌ Please enter your Password',
      'doc_welcome':          '✅ Welcome, Dr.',
      'patient':              'Patient',
      'patient_desc':         'Login or Register to book your clinic token',
      'doctor':               'Doctor / Staff',
      'doctor_desc':          'Log in with your clinic credentials',

      // ── Added: previously-missing keys ─────────────────────
      'ahead_label':          'Ahead',
      'alert_msg':            "You'll get an email alert when your turn is near",
      'alert_ready':          "Alert will be sent when it's your turn",
      'alert_set':            'Alert Set',
      'back_btn':             '← Back',
      'book_token_btn':       '🎟️ Book Token',
      'booking_confirmed':    '✅ Booking Confirmed!',
      'cancel_btn':           'Cancel',
      'change_pass_title':    '🔑 Change Password',
      'clinic_label':         'Clinic',
      'completed':            'Completed',
      'confirm_new_pass':     'Confirm New Password',
      'confirm_pass_hint2':   'Re-enter new password',
      'currently_calling':    'Currently Calling',
      'date_label':           'Date',
      'dates_header':         '📅 Upcoming Clinic Dates',
      'delete_account_title': '⚠️ Delete Account',
      'delete_btn':           'Delete',
      'delete_data_title':    'This will permanently delete:',
      'delete_item1':         '• Your profile and personal details',
      'delete_item2':         '• All your booking history',
      'delete_item3':         '• All your queue records',
      'delete_my_account':    'Delete My Account',
      'delete_warning_long':  'This action cannot be undone. All your data will be permanently removed from CareQueue.',
      'doc_active_queue':     'Active Queue',
      'doc_add_btn':          '+ Add Date',
      'doc_add_date_title':   '📅 Add Clinic Date',
      'doc_add_dates_hint':   'Add a date to start scheduling your clinic queue',
      'doc_closing_time':     'Closing Time',
      'doc_done_next':        '✅ Done — Next',
      'doc_max_patients':     'Max Patients',
      'doc_no_dates_yet':     'No clinic dates added yet',
      'doc_no_queue':         'No patients in queue',
      'doc_opening_time':     'Opening Time',
      'doc_preview_mode':     "👁️ Preview Mode — Queue not started yet",
      'doc_queue_wait':       'Patients will appear here once bookings start',
      'doc_schedule':         'Schedule',
      'doc_schedule_sub':     'Manage your clinic dates',
      'doc_schedule_title':   '📅 Clinic Schedule',
      'doc_scheduled_dates':  'Scheduled Dates',
      'doc_skip':             '⏭️ Skip',
      'doc_tab_queue':        'Queue',
      'doc_tab_schedule':     'Schedule',
      'edit_btn':             '✏️ Edit',
      'edit_profile_title':   '✏️ Edit Profile',
      'enter_pass_confirm':   'Enter your password to confirm',
      'err_old_pass':         '❌ Current password is incorrect',
      'err_pass_wrong':       'Incorrect password',
      'forgot_pass_sub':      'Enter your Gmail to reset your password',
      'forgot_password':      'Forgot Password?',
      'full':                 'Full',
      'fullname_edit_hint':   'Full Name',
      'live_queue_check':     'Check Live Queue',
      'logout_btn':           'Logout',
      'my_details':           'My Details',
      'name_label2':          'Name',
      'new_booking':          '+ New Booking',
      'new_pass_hint':        'New password',
      'new_password_sub':     'Enter your new password below',
      'new_password_title':   '🔑 New Password',
      'no_booking_title':     'No Active Bookings',
      'no_dates_title':       'No upcoming clinic dates',
      'now_label':            'Now',
      'opens_later':          'Opens Later',
      'optional_label':       '(Optional)',
      'otp_expires':          'Code expires in 10 minutes',
      'patient_id_label2':    'Patient ID',
      'profile_clinic':       'Clinic',
      'profile_gmail':        'Gmail',
      'profile_name':         'Name',
      'profile_nic':          'NIC',
      'profile_patient_id':   'Patient ID',
      'profile_phone':        'Phone',
      'queue_status':         'Queue Status',
      'refresh_btn':          '🔄 Refresh',
      'refreshed':            '✅ Refreshed',
      'reset_pass_btn':       'Reset Password',
      'save_btn':             '💾 Save',
      'send_otp_btn':         'Send OTP',
      'status_confirmed':     'Confirmed',
      'summary':              '📋 Booking Summary',
      'tap_live_queue':       'Tap to view live queue →',
      'token_label':          'Token',
      'upcoming_status':      'Upcoming',
      'verify_btn':           'Verify',
      'verify_gmail':         'Verify your Gmail',
      'verify_register_btn':  'Verify & Register',
      'your_password_hint':   'Your password',
      'your_turn_alert':      "🎉 It's your turn now!",
      'your_turn_status':     'Your Turn',
      'auto_refresh':         'Auto-refreshing',
      'booked_count':         'booked',
      'doc_clinic_day':       'Clinic Day',
      'doc_patients':         'patients',
      'max':                  'Max',
      'no_dates_sub':         'no upcoming dates yet',
      'otp_6digits':          'Please enter the 6-digit code',
      'otp_sent_to':          'OTP sent to',
      'pass_reset_success':   'Password reset successful!',
      'patient_id_prefix':    'Patient ID: ',
      'total_tokens':         'total tokens',
      'wait_alert':           'min wait',
      'you_label':            '(You)',
    },

    // ─────────────────────────────────────────────────────────
    //  TAMIL (தமிழ்)
    // ─────────────────────────────────────────────────────────
    AppLang.ta: {

      'app_name':             'CareQueue',
      'app_tagline':          'ஸ்ரீ முருகன் கிளினிக்',

      'lang_en':              'EN',
      'lang_ta':              'தமிழ்',
      'lang_si':              'සිංහල',

      'loading':              'ஏற்றுகிறது...',
      'success':              'வெற்றி',
      'error':                'பிழை',
      'cancel':               'ரத்து செய்',
      'save':                 'சேமி',
      'delete':               'நீக்கு',
      'confirm':              'உறுதிப்படுத்து',
      'yes':                  'ஆம்',
      'no':                   'இல்லை',
      'back':                 'திரும்பு',
      'ok':                   'சரி',
      'close':                'மூடு',
      'logout':               'வெளியேறு',
      'or':                   'அல்லது',

      'tab_book':             'முன்பதிவு',
      'tab_queue':            'வரிசை நிலை',
      'tab_profile':          'சுயவிவரம்',
      'nav_book':             'முன்பதிவு',
      'nav_live':             'வரிசை நிலை',
      'nav_profile':          'சுயவிவரம்',

      'login':                'உள்நுழைவு',
      'register':             'பதிவு செய்',
      'create_account':       '+ கணக்கு தொடங்கு',
      'already_account':      'ஏற்கனவே கணக்கு உள்ளதா?',
      'welcome_back':         'மீண்டும் வரவேற்கிறோம்',

      'login_title':          '🔐 உள்நுழைவு',
      'gmail_label':          'ஜிமெயில்',
      'gmail_hint':           'உங்கள் ஜிமெயில்',
      'gmail_suffix':         '@gmail.com',
      'password_label':       'கடவுச்சொல்',
      'password_hint':        '••••••••',
      'login_btn':            '🚀 உள்நுழை',

      'reg_title':            'பதிவு செய்',
      'personal_details':     '📋 தனிப்பட்ட விவரங்கள்',
      'fullname_label':       'முழு பெயர் *',
      'fullname_hint':        'உங்கள் பெயர் (ஆங்கிலத்தில்)',
      'nic_label':            'தேசிய அடையாள அட்டை *',
      'nic_hint':             '901234567V அல்லது 200012345678',
      'phone_label':          'தொலைபேசி *',
      'phone_hint':           '0756160070',
      'clinic_details':       '🏥 கிளினிக் விவரங்கள்',
      'patient_id_label':     'நோயாளி அட்டை எண் *',
      'patient_id_hint':      'P-0001',
      'password_section':     '🔐 கடவுச்சொல்',
      'confirm_pass_label':   'கடவுச்சொல் உறுதிப்படுத்து *',
      'confirm_pass_hint':    'மீண்டும் உள்ளிடவும்',
      'min_pass_hint':        'குறைந்தது 6 எழுத்துக்கள்',
      'register_btn':         '✅ பதிவு செய்',
      'registered_clinic':    'பதிவு செய்யப்பட்ட கிளினிக்',
      'patient_id_hint_info': '💡 கிளினிக் ஊழியர் கொடுத்த நோயாளி அட்டை எண் (எ.கா. P-0001)',
      'err_login_both':       'ஜிமெயில் மற்றும் கடவுச்சொல் உள்ளிடவும்',

      'err_name_empty':       '❌ பெயர் உள்ளிடவும்',
      'err_name_english':     '❌ ஆங்கில எழுத்துக்கள் மட்டும் (a-z, A-Z)',
      'err_nic_empty':        '❌ தேசிய அடையாள எண் உள்ளிடவும்',
      'err_nic_format':       '❌ 12 இலக்கங்கள் அல்லது 9 இலக்கங்கள் + V',
      'err_phone_empty':      '❌ தொலைபேசி எண் உள்ளிடவும்',
      'err_phone_format':     '❌ 07-ல் ஆரம்பிக்கணும், 10 இலக்கங்கள்',
      'err_gmail_empty':      '❌ ஜிமெயில் உள்ளிடவும்',
      'err_gmail_format':     '❌ சரியான ஜிமெயில் உள்ளிடவும்',
      'err_patid_empty':      '❌ நோயாளி எண் உள்ளிடவும் (P-0001)',
      'err_patid_format':     '❌ வடிவம்: P-0001 (P பெரிய எழுத்து, 4 இலக்கங்கள்)',
      'err_pass_empty':       '❌ குறைந்தது 6 எழுத்துக்கள் வேண்டும்',
      'err_pass_match':       '❌ கடவுச்சொற்கள் பொருந்தவில்லை',
      'err_login_gmail':      '❌ ஜிமெயில் உள்ளிடவும்',
      'err_login_pass':       '❌ கடவுச்சொல் உள்ளிடவும்',

      'available_dates':      'கிளினிக் நாட்கள்',
      'dates_subtitle':       'மருத்துவர் அமைத்த நாட்கள் மட்டும்',
      'book_btn':             '🎫 டோக்கன் முன்பதிவு',
      'selected':             'தேர்ந்தெடுக்கப்பட்டது ✅',
      'max_label':            'அதிகபட்சம்',
      'booked_label':         'பதிவு செய்யப்பட்டது',
      'no_dates':             'இப்போது கிளினிக் நாட்கள் இல்லை.\nமருத்துவர் விரைவில் அமைப்பார்கள்.',
      'booking_open':         'முன்பதிவு செய்யலாம் ✅',
      'booking_closed':       'இன்னும் திறக்கவில்லை',
      'already_booked':       'ஏற்கனவே பதிவு செய்யப்பட்டது ✅',
      'book_success':         '🎉 டோக்கன் பதிவாயிற்று! உங்கள் டோக்கன்:',
      'book_error':           '❌ முன்பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
      'date_not_found':       '❌ தேதி கிடைக்கவில்லை!',

      'live_queue_title':     'நேரடி வரிசை',
      'my_bookings':          'என் முன்பதிவுகள்',
      'current_token':        'தற்போதைய டோக்கன்',
      'your_token':           'உங்கள் டோக்கன்',
      'patients_ahead':       'நோயாளிகள் முன்னால் உள்ளனர்',
      'your_turn':            '🎉 இப்போது உங்கள் முறை!',
      'status_waiting':       'காத்திருக்கிறது',
      'status_done':          'முடிந்தது',
      'status_skipped':       'தவிர்க்கப்பட்டது',
      'no_bookings':          'இன்னும் முன்பதிவு இல்லை.\nமுன்பதிவு தாவலில் டோக்கன் எடுக்கவும்.',
      'clinic_name':          'கிளினிக்',
      'booking_date':         'தேதி',
      'token_no':             'டோக்கன்',
      'status_label':         'நிலை',

      'profile_title':        'என் சுயவிவரம்',
      'edit_profile':         'சுயவிவரம் திருத்து',
      'name_label':           'முழு பெயர்',
      'nic_info':             'தேசிய அடையாள அட்டை',
      'phone_info':           'தொலைபேசி',
      'patient_id':           'நோயாளி எண்',
      'change_password':      'கடவுச்சொல் மாற்று',
      'old_pass_label':       'தற்போதைய கடவுச்சொல்',
      'new_pass_label':       'புதிய கடவுச்சொல்',
      'update_btn':           'சுயவிவரம் புதுப்பி',
      'delete_account':       '🗑️ கணக்கை நீக்கு',
      'delete_confirm':       'கணக்கை நீக்க விரும்புகிறீர்களா? இதை மீட்க முடியாது.',
      'delete_pass_hint':     'கடவுச்சொல் உள்ளிடவும்',
      'update_success':       '✅ சுயவிவரம் புதுப்பிக்கப்பட்டது!',
      'delete_success':       '✅ கணக்கு நீக்கப்பட்டது.',

      'doc_login_title':      'மருத்துவர் உள்நுழைவு',
      'clinic_id_label':      'கிளினிக் ஐடி',
      'clinic_id_hint':       'CLN-XXXX-XXX',
      'doc_name_label':       'மருத்துவர் பெயர்',
      'doc_name_hint':        'Dr. Your Name (English only)',
      'doc_login_btn':        '🏥 மருத்துவர் உள்நுழை',
      'tap_to_fill':          'டெமோ credentials நிரப்ப tap செய்யவும்',
            'demo_clinic_id':       'டெமோ கிளினிக் ஐடி',
      'doc_login_sub':        'கிளினிக் நற்சான்றிதழ்களை மட்டும் பயன்படுத்தவும்',
      'demo_password_label':  'கடவுச்சொல்: doctor123',
      'doc_login_card':       '🔐 மருத்துவர் உள்நுழைவு',
      'doc_login_note':       'கிளினிக் ஊழியர்கள் மட்டுமே உள்நுழைய முடியும். நற்சான்றிதழ் தெரியாவிட்டால் கிளினிக் நிர்வாகியை தொடர்பு கொள்ளவும்.',
      'err_cid_empty':        '❌ கிளினிக் ஐடி உள்ளிடவும்',
      'err_dpass_empty':      '❌ கடவுச்சொல் உள்ளிடவும்',
      'doc_welcome':          '✅ வரவேற்கிறோம், Dr.',
      'patient':              'நோயாளி',
      'patient_desc':         'டோக்கன் முன்பதிவு செய்ய உள்நுழைக அல்லது பதிவு செய்க',
      'doctor':               'மருத்துவர் / ஊழியர்',
      'doctor_desc':          'கிளினிக் நற்சான்றிதழ்களுடன் உள்நுழைக',

      // ── Added: previously-missing keys ─────────────────────
      'ahead_label':          'முன்னால்',
      'alert_msg':            'உங்கள் முறை நெருங்கும் போது மின்னஞ்சல் அறிவிப்பு வரும்',
      'alert_ready':          'உங்கள் முறை வரும்போது அறிவிப்பு அனுப்பப்படும்',
      'alert_set':            'அறிவிப்பு அமைக்கப்பட்டது',
      'back_btn':             '← பின்செல்',
      'book_token_btn':       '🎟️ டோக்கன் முன்பதிவு',
      'booking_confirmed':    '✅ முன்பதிவு உறுதி செய்யப்பட்டது!',
      'cancel_btn':           'ரத்து செய்',
      'change_pass_title':    '🔑 கடவுச்சொல் மாற்று',
      'clinic_label':         'கிளினிக்',
      'completed':            'முடிந்தது',
      'confirm_new_pass':     'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'confirm_pass_hint2':   'புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
      'currently_calling':    'தற்போது அழைக்கப்படுபவர்',
      'date_label':           'தேதி',
      'dates_header':         '📅 வரவிருக்கும் கிளினிக் தேதிகள்',
      'delete_account_title': '⚠️ கணக்கை நீக்கு',
      'delete_btn':           'நீக்கு',
      'delete_data_title':    'இது நிரந்தரமாக நீக்கும்:',
      'delete_item1':         '• உங்கள் சுயவிவரம் மற்றும் தனிப்பட்ட விவரங்கள்',
      'delete_item2':         '• உங்கள் அனைத்து முன்பதிவு வரலாறு',
      'delete_item3':         '• உங்கள் அனைத்து வரிசை பதிவுகள்',
      'delete_my_account':    'எனது கணக்கை நீக்கு',
      'delete_warning_long':  'இந்த செயலை மீட்க முடியாது. உங்கள் தரவு அனைத்தும் CareQueue-இலிருந்து நிரந்தரமாக அகற்றப்படும்.',
      'doc_active_queue':     'செயலில் உள்ள வரிசை',
      'doc_add_btn':          '+ தேதி சேர்',
      'doc_add_date_title':   '📅 கிளினிக் தேதி சேர்',
      'doc_add_dates_hint':   'உங்கள் கிளினிக் வரிசையை திட்டமிட ஒரு தேதியை சேர்க்கவும்',
      'doc_closing_time':     'நிறைவு நேரம்',
      'doc_done_next':        '✅ முடிந்தது — அடுத்தது',
      'doc_max_patients':     'அதிகபட்ச நோயாளிகள்',
      'doc_no_dates_yet':     'இன்னும் கிளினிக் தேதிகள் சேர்க்கப்படவில்லை',
      'doc_no_queue':         'வரிசையில் நோயாளிகள் இல்லை',
      'doc_opening_time':     'தொடக்க நேரம்',
      'doc_preview_mode':     '👁️ முன்னோட்ட முறை — வரிசை இன்னும் தொடங்கவில்லை',
      'doc_queue_wait':       'முன்பதிவுகள் தொடங்கியதும் நோயாளிகள் இங்கே தோன்றுவார்கள்',
      'doc_schedule':         'அட்டவணை',
      'doc_schedule_sub':     'உங்கள் கிளினிக் தேதிகளை நிர்வகிக்கவும்',
      'doc_schedule_title':   '📅 கிளினிக் அட்டவணை',
      'doc_scheduled_dates':  'திட்டமிடப்பட்ட தேதிகள்',
      'doc_skip':             '⏭️ தவிர்',
      'doc_tab_queue':        'வரிசை',
      'doc_tab_schedule':     'அட்டவணை',
      'edit_btn':             '✏️ திருத்து',
      'edit_profile_title':   '✏️ சுயவிவரத்தை திருத்து',
      'enter_pass_confirm':   'உறுதிப்படுத்த உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'err_old_pass':         '❌ தற்போதைய கடவுச்சொல் தவறானது',
      'err_pass_wrong':       'கடவுச்சொல் தவறானது',
      'forgot_pass_sub':      'கடவுச்சொல்லை மீட்க உங்கள் Gmail-ஐ உள்ளிடவும்',
      'forgot_password':      'கடவுச்சொல் மறந்துவிட்டதா?',
      'full':                 'நிறைந்தது',
      'fullname_edit_hint':   'முழு பெயர்',
      'live_queue_check':     'நேரடி வரிசையை பார்க்க',
      'logout_btn':           'வெளியேறு',
      'my_details':           'எனது விவரங்கள்',
      'name_label2':          'பெயர்',
      'new_booking':          '+ புதிய முன்பதிவு',
      'new_pass_hint':        'புதிய கடவுச்சொல்',
      'new_password_sub':     'உங்கள் புதிய கடவுச்சொல்லை கீழே உள்ளிடவும்',
      'new_password_title':   '🔑 புதிய கடவுச்சொல்',
      'no_booking_title':     'செயலில் முன்பதிவுகள் இல்லை',
      'no_dates_title':       'வரவிருக்கும் கிளினிக் தேதிகள் இல்லை',
      'now_label':            'இப்போது',
      'opens_later':          'பின்னர் திறக்கும்',
      'optional_label':       '(விருப்பத்தேர்வு)',
      'otp_expires':          'குறியீடு 10 நிமிடங்களில் காலாவதியாகும்',
      'patient_id_label2':    'நோயாளி ஐடி',
      'profile_clinic':       'கிளினிக்',
      'profile_gmail':        'Gmail',
      'profile_name':         'பெயர்',
      'profile_nic':          'NIC',
      'profile_patient_id':   'நோயாளி ஐடி',
      'profile_phone':        'தொலைபேசி',
      'queue_status':         'வரிசை நிலை',
      'refresh_btn':          '🔄 புதுப்பி',
      'refreshed':            '✅ புதுப்பிக்கப்பட்டது',
      'reset_pass_btn':       'கடவுச்சொல்லை மீட்டமை',
      'save_btn':             '💾 சேமி',
      'send_otp_btn':         'OTP அனுப்பு',
      'status_confirmed':     'உறுதி செய்யப்பட்டது',
      'summary':              '📋 முன்பதிவு சுருக்கம்',
      'tap_live_queue':       'நேரடி வரிசையை பார்க்க தட்டவும் →',
      'token_label':          'டோக்கன்',
      'upcoming_status':      'வரவிருக்கும்',
      'verify_btn':           'சரிபார்',
      'verify_gmail':         'உங்கள் Gmail-ஐ சரிபார்க்கவும்',
      'verify_register_btn':  'சரிபார்த்து பதிவு செய்',
      'your_password_hint':   'உங்கள் கடவுச்சொல்',
      'your_turn_alert':      '🎉 இப்போது உங்கள் முறை!',
      'your_turn_status':     'உங்கள் முறை',
      'auto_refresh':         'தானாக புதுப்பிக்கப்படுகிறது',
      'booked_count':         'முன்பதிவு',
      'doc_clinic_day':       'கிளினிக் நாள்',
      'doc_patients':         'நோயாளிகள்',
      'max':                  'அதிகபட்சம்',
      'no_dates_sub':         'இன்னும் வரவிருக்கும் தேதிகள் இல்லை',
      'otp_6digits':          '6 இலக்க குறியீட்டை உள்ளிடவும்',
      'otp_sent_to':          'OTP அனுப்பப்பட்டது',
      'pass_reset_success':   'கடவுச்சொல் மீட்டமைக்கப்பட்டது!',
      'patient_id_prefix':    'நோயாளி ஐடி: ',
      'total_tokens':         'மொத்த டோக்கன்கள்',
      'wait_alert':           'நிமிடம் காத்திருப்பு',
      'you_label':            '(நீங்கள்)',
    },

    // ─────────────────────────────────────────────────────────
    //  SINHALA (සිංහල)
    // ─────────────────────────────────────────────────────────
    AppLang.si: {

      'app_name':             'CareQueue',
      'app_tagline':          'ශ්‍රී මුරුගන් සායනය',

      'lang_en':              'EN',
      'lang_ta':              'தமிழ்',
      'lang_si':              'සිංහල',

      'loading':              'පූරණය වෙමින්...',
      'success':              'සාර්ථකයි',
      'error':                'දෝෂයකි',
      'cancel':               'අවලංගු',
      'save':                 'සුරකින්න',
      'delete':               'මකන්න',
      'confirm':              'තහවුරු කරන්න',
      'yes':                  'ඔව්',
      'no':                   'නැහැ',
      'back':                 'ආපසු',
      'ok':                   'හරි',
      'close':                'වසන්න',
      'logout':               'පිටවන්න',
      'or':                   'හෝ',

      'tab_book':             'වෙන් කරන්න',
      'tab_queue':            'පෝලිම',
      'tab_profile':          'පැතිකඩ',
      'nav_book':             'වෙන් කරන්න',
      'nav_live':             'පෝලිම',
      'nav_profile':          'පැතිකඩ',

      'login':                'පිවිසෙන්න',
      'register':             'ලියාපදිංචි',
      'create_account':       '+ ගිණුමක් සාදන්න',
      'already_account':      'දැනටමත් ගිණුමක් තිබේද?',
      'welcome_back':         'නැවත සාදරයෙන් පිළිගනිමු',

      'login_title':          '🔐 පිවිසෙන්න',
      'gmail_label':          'ජිමේල්',
      'gmail_hint':           'ඔබේ ජිමේල්',
      'gmail_suffix':         '@gmail.com',
      'password_label':       'මුරපදය',
      'password_hint':        '••••••••',
      'login_btn':            '🚀 පිවිසෙන්න',

      'reg_title':            'ලියාපදිංචි',
      'personal_details':     '📋 පෞද්ගලික තොරතුරු',
      'fullname_label':       'සම්පූර්ණ නම *',
      'fullname_hint':        'ඔබේ නම (ඉංග්‍රීසියෙන්)',
      'nic_label':            'ජාතික හැඳුනුම්පත් අංකය *',
      'nic_hint':             '901234567V හෝ 200012345678',
      'phone_label':          'දුරකථන අංකය *',
      'phone_hint':           '0756160070',
      'clinic_details':       '🏥 සායනය',
      'patient_id_label':     'රෝගී කාඩ් අංකය *',
      'patient_id_hint':      'P-0001',
      'password_section':     '🔐 මුරපදය',
      'confirm_pass_label':   'මුරපදය තහවුරු කරන්න *',
      'confirm_pass_hint':    'නැවත ඇතුළත් කරන්න',
      'min_pass_hint':        'අවම අකුරු 6ක්',
      'register_btn':         '✅ ලියාපදිංචි වන්න',
      'registered_clinic':    'ලියාපදිංචි සායනය',
      'patient_id_hint_info': '💡 සායන කාර්යාල විසින් ලබාදුන් රෝගී කාඩ් අංකය (උදා. P-0001)',
      'err_login_both':       'ජිමේල් සහ මුරපදය ඇතුළත් කරන්න',

      'err_name_empty':       '❌ නම ඇතුළත් කරන්න',
      'err_name_english':     '❌ ඉංග්‍රීසි අකුරු පමණයි (a-z, A-Z)',
      'err_nic_empty':        '❌ හැඳුනුම්පත් අංකය ඇතුළත් කරන්න',
      'err_nic_format':       '❌ ඉලක්කම් 12ක් හෝ ඉලක්කම් 9ක් + V',
      'err_phone_empty':      '❌ දුරකථන අංකය ඇතුළත් කරන්න',
      'err_phone_format':     '❌ 07 සිට ආරම්භ විය යුතුයි, ඉලක්කම් 10ක්',
      'err_gmail_empty':      '❌ ජිමේල් ඇතුළත් කරන්න',
      'err_gmail_format':     '❌ නිවැරදි ජිමේල් ඇතුළත් කරන්න',
      'err_patid_empty':      '❌ රෝගී අංකය ඇතුළත් කරන්න (P-0001)',
      'err_patid_format':     '❌ ආකෘතිය: P-0001 (P ලොකු අකුරෙන්)',
      'err_pass_empty':       '❌ අවම අකුරු 6ක් අවශ්‍යයි',
      'err_pass_match':       '❌ මුරපද නොගැලපේ',
      'err_login_gmail':      '❌ ජිමේල් ඇතුළත් කරන්න',
      'err_login_pass':       '❌ මුරපදය ඇතුළත් කරන්න',

      'available_dates':      'සායන දිනයන්',
      'dates_subtitle':       'වෛද්‍යවරයා විසින් තෝරාගත් දිනයන් පමණයි',
      'book_btn':             '🎫 ටෝකනය වෙන් කරන්න',
      'selected':             'තෝරාගත්තා ✅',
      'max_label':            'උපරිම',
      'booked_label':         'වෙන් කළා',
      'no_dates':             'දැනට සායන දිනයන් නැත.\nවෛද්‍යවරයා ඉක්මනින් දිනයන් යොදයි.',
      'booking_open':         'වෙන් කළ හැකිය ✅',
      'booking_closed':       'තවම විවෘත නැත',
      'already_booked':       'දැනටමත් වෙන් කර ඇත ✅',
      'book_success':         '🎉 ටෝකනය වෙන් කළා! ඔබේ ටෝකනය:',
      'book_error':           '❌ වෙන් කිරීම අසාර්ථකයි. නැවත උත්සාහ කරන්න.',
      'date_not_found':       '❌ දිනය හමු නොවිණි!',

      'live_queue_title':     'සජීවී පෝලිම',
      'my_bookings':          'මගේ වෙන් කිරීම්',
      'current_token':        'වත්මන් ටෝකනය',
      'your_token':           'ඔබේ ටෝකනය',
      'patients_ahead':       'ඔබට ඉදිරියෙන් රෝගීන්',
      'your_turn':            '🎉 දැන් ඔබේ වාරය!',
      'status_waiting':       'රැඳී සිටිනවා',
      'status_done':          'ඉවරයි',
      'status_skipped':       'මඟ හරිනා ලදී',
      'no_bookings':          'තවම වෙන් කිරීම් නැත.\nවෙන් කිරීම් ටැබ් එකෙන් ටෝකනය ගන්න.',
      'clinic_name':          'සායනය',
      'booking_date':         'දිනය',
      'token_no':             'ටෝකනය',
      'status_label':         'තත්ත්වය',

      'profile_title':        'මගේ පැතිකඩ',
      'edit_profile':         'පැතිකඩ සංස්කරණය',
      'name_label':           'සම්පූර්ණ නම',
      'nic_info':             'හැඳුනුම්පත',
      'phone_info':           'දුරකථනය',
      'patient_id':           'රෝගී අංකය',
      'change_password':      'මුරපදය වෙනස් කරන්න',
      'old_pass_label':       'වත්මන් මුරපදය',
      'new_pass_label':       'නව මුරපදය',
      'update_btn':           'පැතිකඩ යාවත්කාලීන කරන්න',
      'delete_account':       '🗑️ ගිණුම මකන්න',
      'delete_confirm':       'ඔබේ ගිණුම මකා දැමීමට කැමතිද? මෙය අස්කර ගත නොහැක.',
      'delete_pass_hint':     'තහවුරු කිරීමට මුරපදය ඇතුළත් කරන්න',
      'update_success':       '✅ පැතිකඩ යාවත්කාලීන විය!',
      'delete_success':       '✅ ගිණුම මකා දමන ලදී.',

      'doc_login_title':      'වෛද්‍ය පිවිසුම',
      'clinic_id_label':      'සායන හැඳුනුම',
      'clinic_id_hint':       'CLN-XXXX-XXX',
      'doc_name_label':       'වෛද්‍යවරයාගේ නම',
      'doc_name_hint':        'Dr. Your Name (English only)',
      'doc_login_btn':        '🏥 වෛද්‍ය පිවිසුම',
      'tap_to_fill':          'ඩෙමෝ credentials පිරවීමට tap කරන්න',
            'demo_clinic_id':       'ඩෙමෝ සායන හැඳුනුම',
      'doc_login_sub':        'සායන ප්‍රමාණපත්‍ර පමණක් භාවිත කරන්න',
      'demo_password_label':  'මුරපදය: doctor123',
      'doc_login_card':       '🔐 වෛද්‍ය පිවිසීම',
      'doc_login_note':       'සායන කාර්යමණ්ඩලයට පමණක් පිවිසිය හැකිය. ප්‍රමාණපත්‍ර නොමැතිනම් සායන ผู้ดูแล හා සම්බන්ධ වන්න.',
      'err_cid_empty':        '❌ සායන හැඳුනුම ඇතුළත් කරන්න',
      'err_dpass_empty':      '❌ මුරපදය ඇතුළත් කරන්න',
      'doc_welcome':          '✅ සාදරයෙන් පිළිගනිමු, Dr.',
      'patient':              'රෝගියා',
      'patient_desc':         'ටෝකනය වෙන් කිරීමට ලොගින් වන්න හෝ ලියාපදිංචි වන්න',
      'doctor':               'වෛද්‍යවරයා / කාර්යමණ්ඩලය',
      'doctor_desc':          'සායන ප්‍රමාණපත්‍ර සමඟ පිවිසෙන්න',

      // ── Added: previously-missing keys ─────────────────────
      'ahead_label':          'ඉදිරියෙන්',
      'alert_msg':            'ඔබේ වාරය ළඟාවන විට ඊමේල් දැනුම්දීමක් ලැබේ',
      'alert_ready':          'ඔබේ වාරය පැමිණි විට දැනුම්දීමක් යවනු ලැබේ',
      'alert_set':            'දැනුම්දීම සකසා ඇත',
      'back_btn':             '← ආපසු',
      'book_token_btn':       '🎟️ ටෝකනය වෙන් කරන්න',
      'booking_confirmed':    '✅ වෙන්කිරීම තහවුරු විය!',
      'cancel_btn':           'අවලංගු කරන්න',
      'change_pass_title':    '🔑 මුරපදය වෙනස් කරන්න',
      'clinic_label':         'සායනය',
      'completed':            'නිමයි',
      'confirm_new_pass':     'නව මුරපදය තහවුරු කරන්න',
      'confirm_pass_hint2':   'නව මුරපදය නැවත ඇතුළත් කරන්න',
      'currently_calling':    'දැනට කැඳවනු ලබන්නේ',
      'date_label':           'දිනය',
      'dates_header':         '📅 ඉදිරි සායන දින',
      'delete_account_title': '⚠️ ගිණුම මකන්න',
      'delete_btn':           'මකන්න',
      'delete_data_title':    'මෙය ස්ථිරවම මකා දමනු ඇත:',
      'delete_item1':         '• ඔබේ පැතිකඩ සහ පුද්ගලික විස්තර',
      'delete_item2':         '• ඔබේ සියලු වෙන්කිරීම් ඉතිහාසය',
      'delete_item3':         '• ඔබේ සියලු පෝලිම් වාර්තා',
      'delete_my_account':    'මගේ ගිණුම මකන්න',
      'delete_warning_long':  'මෙම ක්‍රියාව අහෝසි කළ නොහැක. ඔබේ සියලු දත්ත CareQueue වෙතින් ස්ථිරවම ඉවත් කරනු ලැබේ.',
      'doc_active_queue':     'සක්‍රීය පෝලිම',
      'doc_add_btn':          '+ දිනයක් එක් කරන්න',
      'doc_add_date_title':   '📅 සායන දිනයක් එක් කරන්න',
      'doc_add_dates_hint':   'ඔබේ සායන පෝලිම කාලසටහන් කිරීමට දිනයක් එක් කරන්න',
      'doc_closing_time':     'වසන වේලාව',
      'doc_done_next':        '✅ නිමයි — ඊළඟට',
      'doc_max_patients':     'උපරිම රෝගීන්',
      'doc_no_dates_yet':     'තවම සායන දින එකතු කර නැත',
      'doc_no_queue':         'පෝලිමේ රෝගීන් නැත',
      'doc_opening_time':     'විවෘත වේලාව',
      'doc_preview_mode':     '👁️ පෙරදසුන් ප්‍රකාරය — පෝලිම තවම ආරම්භ වී නැත',
      'doc_queue_wait':       'වෙන්කිරීම් ආරම්භ වූ පසු රෝගීන් මෙහි දිස්වනු ඇත',
      'doc_schedule':         'කාලසටහන',
      'doc_schedule_sub':     'ඔබේ සායන දින කළමනාකරණය කරන්න',
      'doc_schedule_title':   '📅 සායන කාලසටහන',
      'doc_scheduled_dates':  'නියමිත දින',
      'doc_skip':             '⏭️ මඟ හරින්න',
      'doc_tab_queue':        'පෝලිම',
      'doc_tab_schedule':     'කාලසටහන',
      'edit_btn':             '✏️ සංස්කරණය',
      'edit_profile_title':   '✏️ පැතිකඩ සංස්කරණය',
      'enter_pass_confirm':   'තහවුරු කිරීමට ඔබේ මුරපදය ඇතුළත් කරන්න',
      'err_old_pass':         '❌ වත්මන් මුරපදය වැරදිය',
      'err_pass_wrong':       'මුරපදය වැරදිය',
      'forgot_pass_sub':      'මුරපදය යළි පිහිටුවීමට ඔබේ Gmail ඇතුළත් කරන්න',
      'forgot_password':      'මුරපදය අමතකද?',
      'full':                 'පිරී ඇත',
      'fullname_edit_hint':   'සම්පූර්ණ නම',
      'live_queue_check':     'සජීවී පෝලිම බලන්න',
      'logout_btn':           'ඉවත් වන්න',
      'my_details':           'මගේ විස්තර',
      'name_label2':          'නම',
      'new_booking':          '+ නව වෙන්කිරීම',
      'new_pass_hint':        'නව මුරපදය',
      'new_password_sub':     'ඔබේ නව මුරපදය පහත ඇතුළත් කරන්න',
      'new_password_title':   '🔑 නව මුරපදය',
      'no_booking_title':     'සක්‍රීය වෙන්කිරීම් නැත',
      'no_dates_title':       'ඉදිරි සායන දින නැත',
      'now_label':            'දැන්',
      'opens_later':          'පසුව විවෘත වේ',
      'optional_label':       '(විකල්ප)',
      'otp_expires':          'කේතය මිනිත්තු 10කින් කල් ඉකුත් වේ',
      'patient_id_label2':    'රෝගී හැඳුනුම',
      'profile_clinic':       'සායනය',
      'profile_gmail':        'Gmail',
      'profile_name':         'නම',
      'profile_nic':          'ජා.හැ.අංකය',
      'profile_patient_id':   'රෝගී හැඳුනුම',
      'profile_phone':        'දුරකථනය',
      'queue_status':         'පෝලිම් තත්ත්වය',
      'refresh_btn':          '🔄 නවීකරණය',
      'refreshed':            '✅ නවීකරණය විය',
      'reset_pass_btn':       'මුරපදය යළි පිහිටුවන්න',
      'save_btn':             '💾 සුරකින්න',
      'send_otp_btn':         'OTP යවන්න',
      'status_confirmed':     'තහවුරු කර ඇත',
      'summary':              '📋 වෙන්කිරීම් සාරාංශය',
      'tap_live_queue':       'සජීවී පෝලිම බැලීමට තට්ටු කරන්න →',
      'token_label':          'ටෝකනය',
      'upcoming_status':      'ඉදිරි',
      'verify_btn':           'තහවුරු කරන්න',
      'verify_gmail':         'ඔබේ Gmail තහවුරු කරන්න',
      'verify_register_btn':  'තහවුරු කර ලියාපදිංචි වන්න',
      'your_password_hint':   'ඔබේ මුරපදය',
      'your_turn_alert':      '🎉 දැන් ඔබේ වාරයයි!',
      'your_turn_status':     'ඔබේ වාරය',
      'auto_refresh':         'ස්වයංක්‍රීයව යාවත්කාලීන වේ',
      'booked_count':         'වෙන් කර ඇත',
      'doc_clinic_day':       'සායන දිනය',
      'doc_patients':         'රෝගීන්',
      'max':                  'උපරිම',
      'no_dates_sub':         'තවම ඉදිරි දින නැත',
      'otp_6digits':          'කරුණාකර ඉලක්කම් 6 කේතය ඇතුළත් කරන්න',
      'otp_sent_to':          'OTP යවන ලද්දේ',
      'pass_reset_success':   'මුරපදය නැවත සකසන ලදී!',
      'patient_id_prefix':    'රෝගී හැඳුනුම: ',
      'total_tokens':         'මුළු ටෝකන්',
      'wait_alert':           'මිනිත්තු රැඳී සිටීම',
      'you_label':            '(ඔබ)',
    },
  };
}

// ══════════════════════════════════════════════════════════════
//  Language Switcher Widget — place in any screen AppBar/header
// ══════════════════════════════════════════════════════════════
class LangSwitcher extends StatelessWidget {
  final Color? activeColor;
  final Color? inactiveColor;
  const LangSwitcher({Key? key, this.activeColor, this.inactiveColor}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<AppLang>(
      valueListenable: langNotifier,
      builder: (_, cur, __) {
        return Container(
          margin: const EdgeInsets.only(right: 8),
          padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 4),
          decoration: BoxDecoration(
            color: Colors.white.withOpacity(0.15),
            borderRadius: BorderRadius.circular(20),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: AppLang.values.map((lang) {
              final active = cur == lang;
              final label  = lang == AppLang.en ? 'EN'
                           : lang == AppLang.ta ? 'த'
                           : 'සි';
              return GestureDetector(
                onTap: () => Lang.set(lang),
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: active ? Colors.white : Colors.transparent,
                    borderRadius: BorderRadius.circular(14),
                  ),
                  child: Text(label,
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: active
                        ? (activeColor ?? const Color(0xFF1a6b5a))
                        : (inactiveColor ?? Colors.white),
                    ),
                  ),
                ),
              );
            }).toList(),
          ),
        );
      },
    );
  }
}
